version: "3.3"

services:
  app:
    build: .
    container_name: rcmltb
    command: bash start.sh
    volumes:
      - /usr/src/app/downloads:/usr/src/app/downloads:rw # optional
    ports:
      - "80:80" # qbittorrent selection webserver
      - "81:81" # local mirror files webserver
      - "8080:8080" # rclone serve index webserver
    restart: on-failure
      
      
